# Generated by Django 4.1.5 on 2023-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='units',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=19),
        ),
    ]
