# Generated by Django 4.1.5 on 2023-01-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budgetitem_amount_alter_budgetitem_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
